### ISSUE TITLE
Is /data/db required?

### ISSUE THREAD

**Issue by mrinnetmaki** [Sensotrend/sensotrend-tidepool#2]
http://developer.tidepool.io/starting-up-services/ states

> If you’re performing a new MongoDB installation on a Mac (using brew install mongodb), you also need to do the following:
> 
> Run sudo mkdir -p /data/db
> Set permissions for /data/db to the local user using sudo chown <your username> /data/db

However, the setup scripts at tools repo install vagrant using apt-get and don't create such folders.

**Comment by mrinnetmaki** [comment]
When I create /data/db library, some mongo stuff is created there.

**Comment by ollimk** [comment]
On linux using mongo got from apt-get seems to work without. Except if you do the mistake that I did and shut that down that mongo and let tools/runservers -script start a new one. Default folder seems to be /data/db so that explains it...

**Comment by mrinnetmaki** [comment]
@ollimk indicated this is not necessary. Tests verify.
